### ISSUE TITLE
GAE的支持

### ISSUE THREAD

**Issue by vaemon** [fxsjy/jieba#109]
请问jieba可放上GAE吗？谢谢。

**Comment by astromme** [comment]
I think what this issue is saying is "Can Jieba be used on Google App Engine?" and jannson's response is "well, creating the temp files doesn't work".

That's also what I'm finding:

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~dokibo-dict/20161021t175549.396505411313804719/lib/jieba/__init__.py", line 123, in initialize
    self.tmp_dir or tempfile.gettempdir(), cache_file)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/tempfile.py", line 45, in PlaceHolder
    raise NotImplementedError("Only tempfile.TemporaryFile is available for use")
NotImplementedError: Only tempfile.TemporaryFile is available for use
```

What approach could be used to fix this?

**Comment by liantian-cn** [comment]
@astromme 

Maybe you can make a patch to gae....tempfile.py

like this :  https://github.com/liantian-cn/jieba-gae/blob/master/lib/tempfile_gae.py

Then just replace `import tempfile` for` import tempfile_gae as tempfile` , in the error of the file.

like this : https://github.com/liantian-cn/jieba-gae/blob/master/lib/jieba/__init__.py

It looks good now : https://jieba.liantian.me/

note:

If you replace `tempfile.py` directly, do not use` tempfile_gae.py`, the development service is not available.
