### ISSUE TITLE
分词部分报错

### ISSUE THREAD

**Issue by logbird** [fxsjy/jieba#207]
一个很奇怪的问题
我的代码如下：
import sys 
reload(sys)
sys.setdefaultencoding("utf-8")
sys.path.append("../")
import jieba
jieba.setLogLevel(60)
jieba.load_userdict("dict.txt")
import jieba.analyse

test_sent = sys.stdin.read()
tags = jieba.analyse.extract_tags(test_sent, topK=6)
print ",".join(tags)

保存为 test.py
在 用户根目录执行的时候 执行成功，成功提取出结果

我将test.py 和 dict.txt 复制到 /data/www/目录下执行 就会报错
Traceback (most recent call last):
  File "./keyword.py", line 9, in <module>
    import jieba.analyse
  File "/usr/local/lib/python2.7/dist-packages/jieba/analyse/**init**.py", line 9, in <module>
    from textrank import textrank
  File "/usr/local/lib/python2.7/dist-packages/jieba/analyse/textrank.py", line 5, in <module>
    import collections
  File "/usr/lib/python2.7/collections.py", line 10, in <module>
    from keyword import iskeyword as _iskeyword
  File "/data/www/spider/keyword.py", line 12, in <module>
    tags = jieba.analyse.extract_tags(test_sent, topK=6)
AttributeError: 'module' object has no attribute 'analyse'

我安装jieba的时候 使用 pip安装
pip install jieba
真的搞不懂原因了，求解

**Comment by gumblex** [comment]
你的 keyword.py (原 test.py) 与标准库重名了
./keyword.py 引用 jieba.analyse 引用 textrank 引用 collections 引用 keyword，然后本目录的模块优先搜索，就用你的 keyword.py 了。
解决方法：改名

**Comment by logbird** [comment]
谢了我之前的时候 经过测试发现确实是这个问题。。非常感谢
