### ISSUE TITLE
新版本无法载入自定义词库

### ISSUE THREAD

**Issue by reee** [fxsjy/jieba#244]
代码如下：

	#encoding=utf-8
	import jieba
	import jieba.posseg as posseg

	jieba.load_userdict("/data/paper/keywords/user_dict.txt")

	words = posseg.cut("在现代社会中，免洗消毒液的使用越来越普遍，消毒液中所含的肉豆蔻酸异丙酯、丙二醇和乙醇等成分可增强皮肤的渗透性。")

	for w in words:
		print('%s %s' % (w.word, w.flag))

报错 
	Building prefix dict from /usr/lib/python2.7/site-packages/jieba/dict.txt ...
	Loading model from cache /tmp/jieba.cache
	Loading model cost 0.296606063843 seconds.
	Prefix dict has been built succesfully.
	Traceback (most recent call last):
	  File "./jieba-test.py", line 5, in <module>
		jieba.load_userdict("/data/paper/keywords/user_dict.txt")
	  File "/usr/lib/python2.7/site-packages/jieba/__init__.py", line 119, in wrapped
		return fn(*args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/jieba/__init__.py", line 312, in load_userdict
		add_word(*tup)
	  File "/usr/lib/python2.7/site-packages/jieba/__init__.py", line 116, in wrapped
		return fn(*args, **kwargs)
	TypeError: add_word() takes at most 3 arguments (4 given)

之前还工作的好好的。user_dict.txt 类似于这样的：

	酞 10 n
	 酞酐 20 n
	 酞磺胺噻唑 50 n
	 酞磺醋胺 40 n
	 酞基 20 n
	 酞己炔酯 40 n
	 酞腈 20 n
	 酞菁 20 n
	 酞菁二(吡啶)铁(II)络合物 150 n
	 酞菁镉 30 n
	 酞菁蓝 30 n
	 酞菁锂 30 n
	 酞菁镁 30 n
	 酞菁染料 40 n
	 酞菁素艳蓝 50 n
	 酞菁锡(II) 70 n
	 酞菁亚铁 40 n
	 酞菁铟 30 n
	 酞菁银 30 n
	 酞类染料 40 n
	 酞嗪 20 n
	 酞醛 20 n
	 酞酸 20 n
	 酞酸丁苄酯 50 n
	 酞酸二苯酯 50 n
	 酞酸二丙酯 50 n
	 酞酸二环己酯 60 n
	 酞酸二甲酯 50 n
	 酞酸二壬酯 50 n
	 酞酸二辛酯 50 n
	 酞酸二乙酯 50 n
	 酞酸二异癸酯 60 n
	 酞酮酸 30 n
	 酞醯胺醯基 50 n
	 酞醯基 30 n
	 酞醯亚胺基 50 n
	 酞酰胺 30 n
	 酞酰氯 30 n
	 酞亚胺 30 n

其中优先级是按词语长度用脚本自动生成的，给予长词更高的优先级。

**Comment by reee** [comment]
我发现了。似乎是自定义词库本身的问题
