### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by zzr0427** [fxsjy/jieba#268]
运行test目录下的demo.py时出现了
========================================
1. 分词
----------------------------------------
Building prefix dict from /usr/local/lib/python2.7/dist-packages/jieba/dict.txt ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.000440835952759 seconds.
Prefix dict has been built succesfully.
Full Mode: 我/ 来/ 到/ 北/ 京/ 清/ 华/ 大/ 学
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    print("Default Mode: " + "/ ".join(seg_list))  # 默认模式
  File "/usr/local/lib/python2.7/dist-packages/jieba/__init__.py", line 274, in cut
    for word in cut_block(blk):
  File "/usr/local/lib/python2.7/dist-packages/jieba/__init__.py", line 199, in __cut_DAG
    calc(sentence, DAG, route=route)
  File "/usr/local/lib/python2.7/dist-packages/jieba/__init__.py", line 144, in calc
    logtotal = log(total)
ValueError: math domain error
这是因为什么？
这是用python2还是python3写的？

**Comment by gumblex** [comment]
词典好像没成功加载，删掉 /tmp/jieba.cache，下载最新版试试。
最新版 Python 2/3 均兼容

**Comment by Jack-Roc** [comment]
用 最新版的jieba0.42.1     pyinstaller  打包报错  缺少 dict.txt   解决后     
再次打包   报 这个     ValueError: math domain error

**Comment by goingHan** [comment]
可以手动改一下logtotal = log(total)这个， 改成  log(max(total, 1e-12)) , 能避免这个报错

**Comment by manother** [comment]
邮件已收到~
