### ISSUE TITLE
导入词典是报错

### ISSUE THREAD

**Issue by GiterLI** [fxsjy/jieba#279]
jieba.load_userdict('entity_dic.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jieba/__init__.py", line 119, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jieba/__init__.py", line 334, in load_userdict
    logger.debug('%s at line %s %s' % (f_name, lineno, line))
NameError: global name 'f_name' is not defined

我是用pip安装的。。。

**Comment by gumblex** [comment]
应该是 #257 的问题，还是升级版本吧。

**Comment by GiterLI** [comment]
现在版本是0.36

**Comment by gumblex** [comment]
这个问题出现在 0.36 整个版本
