### ISSUE TITLE
Failed to load dict.txt distributed in egg or zip format

### ISSUE THREAD

**Issue by QingfengYang** [fxsjy/jieba#308]
Building prefix dict from E:\Download\jieba-0.37\jieba-0.37\dist\jieba-0.37-py3.4.egg\jieba\dict.txt ...
Traceback (most recent call last):
  File "X:/python/pylab/labtest.py", line 68, in <module>
    print("Full Mode: " + "/".join(seg_list))
  File "E:\Download\jieba-0.37\jieba-0.37\dist\jieba-0.37-py3.4.egg\jieba\__init__.py", line 299, in cut
  File "E:\Download\jieba-0.37\jieba-0.37\dist\jieba-0.37-py3.4.egg\jieba\__init__.py", line 195, in __cut_all
  File "E:\Download\jieba-0.37\jieba-0.37\dist\jieba-0.37-py3.4.egg\jieba\__init__.py", line 177, in get_DAG
  File "E:\Download\jieba-0.37\jieba-0.37\dist\jieba-0.37-py3.4.egg\jieba\__init__.py", line 166, in check_initialized
  File "E:\Download\jieba-0.37\jieba-0.37\dist\jieba-0.37-py3.4.egg\jieba\__init__.py", line 127, in initialize
  File "C:\Python34\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\Download\\jieba-0.37\\jieba-0.37\\dist\\jieba-0.37-py3.4.egg\\jieba\\dict.txt'

**Comment by QingfengYang** [comment]
在hadoop/spark上使用的时候，需要打包成zip或者egg格式，但是一启动就出现
15/11/12 13:40:22 INFO scheduler.DAGScheduler: Job 1 failed: take at SerDeUtil.scala:235, took 12.081458 s
Traceback (most recent call last):
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 142, in <module>
    valueConverter=valueConv)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/lib/spark/python/pyspark/rdd.py", line 1274, in saveAsNewAPIHadoopDataset
    keyConverter, valueConverter, True)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.saveAsHadoopDataset.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4, gs-server-1010): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 101, in main
    process()
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 96, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/serializers.py", line 236, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 119, in calTagByPartition
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 63, in calculateTags
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 47, in calTagsForPvTitles
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 299, in cut
    for word in cut_block(blk):
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 195, in __cut_all
    dag = self.get_DAG(sentence)
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 177, in get_DAG
    self.check_initialized()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 166, in check_initialized
    self.initialize()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 141, in initialize
    self.FREQ, self.total = self.gen_pfdict(abs_path)
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 73, in gen_pfdict
    with open(f_name, 'rb') as f:
IOError: [Errno 20] Not a directory: u'/hdfs/disk2/yarn/nm/usercache/yangqingfeng/appcache/application_1439499983891_11231/container_1439499983891_11231_01_000005/jieba-0.37-py3.4.egg/jieba/dict.txt'

	at org.apache.spark.api.python.PythonRDD$$anon$1.read(PythonRDD.scala:135)
	at org.apache.spark.api.python.PythonRDD$$anon$1.<init>(PythonRDD.scala:176)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:94)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
这个问题的原因是：结巴分词 使用“__file__"属性来定位dict.txt；但是当python文件被打包成egg之后，dict.txt已经不是一个文件了。
http://stackoverflow.com/questions/3071327/problem-accessing-config-files-within-a-python-egg
貌似要使用 pkg_resources 才能解决这个问题。不知道各位大神什么能否fix这个问题？

**Comment by fxsjy** [comment]
你可以自己定义词典的位置， 如下：

tk = jieba.Tokenizer('/opt/jieba/dict.txt')  
tk.cut("hello world")

**Comment by gumblex** [comment]
这个问题应该可以直接修

**Comment by QingfengYang** [comment]
@fxsjy 恩，这个方法是可以行得通。这样子别人使用我的程序的时候，如果自己引入jieba使用还是不行的。而且，这样子我需要在每台机器上都放这个文件，在分布式集群环境搞不了。我改了一下；
jieba的 __init__.py 
1)运行时 从egg中读出这个文件
2)写到临时文件，并将 DEFAULT_DICT = rewriteDictlocatioin
import pkg_resources
dict_data = pkg_resources.resource_string(__name__, "dict.txt")
rewriteDictlocatioin = os.path.join(os.getcwd(), "dict.txt")
print("## -- extract dict from egg, and rewrite to:", rewriteDictlocatioin)
import io
with io.open(rewriteDictlocatioin, 'wb') as dictTmpFile:
    dictTmpFile.write(dict_data)

DEFAULT_DICT = rewriteDictlocatioin

**Comment by gumblex** [comment]
@QingfengYang 试试 #309 修复后的代码

**Comment by QingfengYang** [comment]
@gumblex 这个版本有问题，完整日志如下：
15/11/13 11:38:52 WARN scheduler.TaskSetManager: Lost task 17.0 in stage 2.0 (TID 19, gs-server-1000): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 101, in main
    process()
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 96, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/serializers.py", line 236, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 119, in calTagByPartition
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 63, in calculateTags
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 47, in calTagsForPvTitles
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 301, in cut
    for word in cut_block(blk):
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 197, in __cut_all
    dag = self.get_DAG(sentence)
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 179, in get_DAG
    self.check_initialized()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 168, in check_initialized
    self.initialize()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 143, in initialize
    self.FREQ, self.total = self.gen_pfdict(self.get_dict_file())
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 74, in gen_pfdict
    with f:
AttributeError: 'cStringIO.StringI' object has no attribute '__exit__'

	at org.apache.spark.api.python.PythonRDD$$anon$1.read(PythonRDD.scala:135)
	at org.apache.spark.api.python.PythonRDD$$anon$1.<init>(PythonRDD.scala:176)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:94)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

15/11/13 11:38:52 INFO scheduler.TaskSetManager: Lost task 27.0 in stage 2.0 (TID 29) on executor gs-server-1000: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 101, in main
    process()
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 96, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/serializers.py", line 236, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 119, in calTagByPartition
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 63, in calculateTags
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 47, in calTagsForPvTitles
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 301, in cut
    for word in cut_block(blk):
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 197, in __cut_all
    dag = self.get_DAG(sentence)
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 179, in get_DAG
    self.check_initialized()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 168, in check_initialized
    self.initialize()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 143, in initialize
    self.FREQ, self.total = self.gen_pfdict(self.get_dict_file())
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 74, in gen_pfdict
    with f:
AttributeError: 'cStringIO.StringI' object has no attribute '__exit__'
) [duplicate 1]
15/11/13 11:38:52 INFO scheduler.TaskSetManager: Lost task 7.0 in stage 2.0 (TID 9) on executor gs-server-1000: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 101, in main
    process()
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/worker.py", line 96, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/jars/spark-assembly-1.3.0-cdh5.4.2-hadoop2.6.0-cdh5.4.2.jar/pyspark/serializers.py", line 236, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 119, in calTagByPartition
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 63, in calculateTags
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 47, in calTagsForPvTitles
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 301, in cut
    for word in cut_block(blk):
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 197, in __cut_all
    dag = self.get_DAG(sentence)
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 179, in get_DAG
    self.check_initialized()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 168, in check_initialized
    self.initialize()
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 143, in initialize
    self.FREQ, self.total = self.gen_pfdict(self.get_dict_file())
  File "./jieba-0.37-py3.4.egg/jieba/__init__.py", line 74, in gen_pfdict
    with f:
AttributeError: 'cStringIO.StringI' object has no attribute '__exit__'
) [duplicate 2]
15/11/13 11:38:52 INFO scheduler.TaskSetManager: Starting task 7.1 in stage 2.0 (TID 35, gs-server-1006, PROCESS_LOCAL, 1387 bytes)
15/11/13 11:38:52 INFO scheduler.TaskSetManager: Starting task 27.1 in stage 2.0 (TID 36, gs-server-1004, PROCESS_LOCAL, 1387 bytes)
15/11/13 11:38:52 INFO scheduler.TaskSetManager: Starting task 17.1 in stage 2.0 (TID 37, gs-server-1005, PROCESS_LOCAL, 1387 bytes)
^CTraceback (most recent call last):
  File "/home/yangqingfeng/pyspark/pySparkSample.py", line 142, in <module>
    valueConverter=valueConv)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/lib/spark/python/pyspark/rdd.py", line 1274, in saveAsNewAPIHadoopDataset
    keyConverter, valueConverter, True)
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 536, in __call__
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 364, in send_command
  File "/opt/cloudera/parcels/CDH-5.4.2-1.cdh5.4.2.p0.2/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 473, in send_command
  File "/usr/lib64/python2.6/socket.py", line 433, in readline

**Comment by liaicheng** [comment]
jieba.load_userdict('mydict.txt')后，发现在spark里面，该词典没有加载成功，不知如何解决？
