### ISSUE TITLE
用户词典出现错误

### ISSUE THREAD

**Issue by Thidtc** [fxsjy/jieba#322]
在使用用户词典时，运行样例，若是有词包含空格，例如样例中的
Edu Trust认证 2000
则运行时会出现如下的错误：

Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    jieba.load_userdict("userdict.txt")
  File "/usr/local/lib/python2.7/dist-packages/jieba/__init__.py", line 381, in load_userdict
    f.name, lineno, line))
ValueError

**Comment by gumblex** [comment]
pypi 上的版本没更新
