### ISSUE TITLE
jieba.dt找不到

### ISSUE THREAD

**Issue by 1f9763** [fxsjy/jieba#347]
import jieba
  File "C:\Python27\lib\site-packages\jieba\__init__.py", line 9, in <module>
    import logging
  File "C:\Python27\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "C:\Python27\lib\collections.py", line 10, in <module>
    from keyword import iskeyword as _iskeyword
  File "C:\Users\2200621\Dropbox\Learning\Python\py\spider\keyword.py", line 4,
in <module>
    import jieba.analyse
  File "C:\Python27\lib\site-packages\jieba\analyse\__init__.py", line 2, in <mo
dule>
    from .tfidf import TFIDF
  File "C:\Python27\lib\site-packages\jieba\analyse\tfidf.py", line 5, in <modul
e>
    import jieba.posseg
  File "C:\Python27\lib\site-packages\jieba\posseg\__init__.py", line 257, in <m
odule>
    dt = POSTokenizer(jieba.dt)
AttributeError: 'module' object has no attribute 'dt'

**Comment by Linusp** [comment]
如果我没记错，应该是 0.37 之后才加上 `dt` ，不妨检查下 jieba 的版本

**Comment by cliuxinxin** [comment]
同样遇到这个问题。

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    import jieba
  File "C:\Python27\lib\site-packages\jieba\__init__.py", line 9, in <module>
    import logging
  File "C:\Python27\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "C:\Python27\lib\collections.py", line 10, in <module>
    from keyword import iskeyword as _iskeyword
  File "D:\python\jieba\keyword.py", line 7, in <module>
    import jieba.posseg
  File "C:\Python27\lib\site-packages\jieba\posseg\__init__.py", line 257, in <module>
    dt = POSTokenizer(jieba.dt)
AttributeError: 'module' object has no attribute 'dt'

**Comment by seaguest** [comment]
我也碰到楼上的问题，之前碰到的是找不到jieba.analyse模块。
重新安装之后就遇到楼上的问题，也许以来顺序的问题？

我是用的是python2.7．

**Comment by Linusp** [comment]
@seaguest 和 Python 版本没关系，和 jieba 版本有关系， `import jieba` 后执行 `print jieba.__version__` 和 `print jieba.__file__` 看看就知道了

**Comment by seaguest** [comment]
@Linusp 

经过试验证明，是我的一个文件命名的问题。
我有一个文件叫keyword.py，这个文件导致import jieba出错，当我吧名字改成keywords.py,问题就解决了。不知道这背后是什么原因。

**Comment by glglgithub** [comment]
@seaguest , thanks. your solution works. It happens to me as well.
