### ISSUE TITLE
你好~ 在打包程序的时候出现了问题

### ISSUE THREAD

**Issue by lisnb** [fxsjy/jieba#35]
你好~我在我的一个小项目里使用了结巴分词，首先对您的努力表示感谢~

我在使用py2exe打包我的程序的时候，其他的模块都没有出现问题，打包能够成功，但在运行的时候一直显示

IOError: [Errno 2] No such file or directory: 'E:\python\links\romeo\dist\l
ibrary.zip\jieba\finalseg\prob_start.py'

我单独写了一个.py文件，只有一句话：
import jieba 
seg=jieba.cut('hello jieba')

打包，但运行的时候也是上面的那个结果。
![image](https://f.cloud.github.com/assets/3349741/360329/71333cde-a18d-11e2-82f5-7fc3ca3ee61a.png)

我不知道您是否打包过使用了结巴的程序，如果有，您遇到过这样的问题吗？
或者您知道问题可能出现在哪吗？
谢谢啦~

**Comment by shymaggie** [comment]
Building prefix dict from C:\Users\g4320\Desktop\qt\test\dist\dict.txt ...
Loading model from cache c:\users\g4320\appdata\local\temp\jieba.ua7197607c9829a7854ca3e54b4005544.cache
Loading model cost 0.355 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from jieba import analyse
  File "jieba\analyse\__init__.pyo", line 9, in <module>
  File "jieba\analyse\tfidf.pyo", line 65, in __init__
  File "jieba\analyse\tfidf.pyo", line 42, in __init__
  File "jieba\analyse\tfidf.pyo", line 47, in set_new_path
IOError: [Errno 2] No such file or directory: 'C:\\Users\\g4320\\Desktop\\qt\\test\\dist\\library.zip\\jieba\\analyse\\idf.txt
-------------
idf还是不行

**Comment by Jie-Yuan** [comment]
还是不行哈

**Comment by shouldsee** [comment]
个人经验,win上面打包的话用pyinstaller比较简单一些,py2exe和cxfreeze我都没太学会.
