### ISSUE TITLE
载入vocab.txt报错

### ISSUE THREAD

**Issue by xiaoniuzilo** [fxsjy/jieba#601]
>>> import synonyms
>> Synonyms load wordseg dict [D:\python34\lib\site-packages\synonyms\data\vocab
.txt] ...
Traceback (most recent call last):
  File "D:\python34\lib\site-packages\jieba\posseg\__init__.py", line 105, in lo
ad_word_tag
    word, _, tag = line.split(" ")
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python34\lib\site-packages\synonyms\__init__.py", line 85, in <module
>
    _tokenizer.initialize(tokenizer_dict)
  File "D:\python34\lib\site-packages\jieba\posseg\__init__.py", line 95, in ini
tialize
    self.load_word_tag(self.tokenizer.get_dict_file())
  File "D:\python34\lib\site-packages\jieba\posseg\__init__.py", line 109, in lo
ad_word_tag
    'invalid POS dictionary entry in %s at Line %s: %s' % (f_name, lineno, line)
)
ValueError: invalid POS dictionary entry in D:\python34\lib\site-packages\synony
ms\data\vocab.txt at Line 333405: 福荫 1 v 2 n

好像是jieba不支持多个词性，后来手工修改，每个词只保留一个词性，就没有这个bug了

**Comment by WorldWarII** [comment]
我也遇到了这个问题，也是在使用synonyms这个包的时候出现的。但是不知道原因具体的原因
