### ISSUE TITLE
Java中如何调用jieba

### ISSUE THREAD

**Issue by munandong** [fxsjy/jieba#79]
public static void main(String args[]) {
        PythonInterpreter interpreter = new PythonInterpreter();
        interpreter.execfile("D:\test\test.py");
    }
//报错信息如下
Exception in thread "main" Traceback (most recent call last):
  File "D:\test\test.py", line 4, in <module>
    import jieba
  File "C:\Python27\Lib\site-packages\jieba__init__.py", line 6, in <module>
    import finalseg
  File "C:\Python27\Lib\site-packages\jieba\finalseg__init__.py", line 6, in <module>
    import prob_emit
java.lang.ArrayIndexOutOfBoundsException: 51530

**Comment by yifanhunter** [comment]
两者吐出的结果不一致啊~~~~
