### ISSUE TITLE
Change path to jieba.cache

### ISSUE THREAD

**Issue by loretoparisi** [fxsjy/jieba#884]
I would like to switch the default path of `jieba.cache` file to my destination
Currently Jieba is dumping the file to a [temporary folder](https://github.com/fxsjy/jieba/blob/1e20c89b66f56c9301b0feed211733ffaa1bd72a/jieba/__init__.py#L147) at every start:

```
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
```

while I would like to have the file dumped once in a shared folder.

In my code I just do

```python
import jieba
# ...
jieba.cut(tok, cut_all=False)
```

so I do not have any entry point to explicitly initialize Jieba elsewhere.

**Comment by tshu-w** [comment]
change dir as you want:
```python
import jieba
jieba.dt.tmp_dir = expanduser("~/.cache/jieba")
```

**Comment by loretoparisi** [comment]
@tshu-w Thanks I have tried but I get now

```
Dumping model to file cache /root/jieba/jieba.cache
Dump cache file failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jieba/__init__.py", line 150, in initialize
    fd, fpath = tempfile.mkstemp(dir=tmpdir)
  File "/usr/local/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/root/jieba/tmpav8rwj0e'
Loading model cost 1.379 seconds.
```

After I did 
```python
import jieba
...
# LP: custom jieba dict path
MXM_ROOT = os.getenv('ROOT', '/root')
jieba.dt.tmp_dir = os.path.join(ROOT,'jieba')
....
if lang == 'zh':
        # jieba -d
        seg_list = jieba.cut(tok, cut_all=False)
        tok = " ".join(seg_list)
        ....
```

**Comment by tshu-w** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/root/jieba/tmpav8rwj0e'

This error is because there is no folder "/root/jieba", 

```python
import jieba
import os
# LP: custom jieba dict path
MXM_ROOT = os.getenv('ROOT', '/root')
jieba.dt.tmp_dir = os.path.join(ROOT, 'jieba')
os.mkdirs(jieba.dt.tmp_dir, exist_ok=True)
```

**Comment by loretoparisi** [comment]
Correct thanks now it works fine!
